VSCP_PRIORITY_0 =  0x00
VSCP_PRIORITY_1 =  0x20
VSCP_PRIORITY_2 =  0x40
VSCP_PRIORITY_3 =  0x60
VSCP_PRIORITY_4 =  0x80
VSCP_PRIORITY_5 =  0xA0
VSCP_PRIORITY_6 =  0xC0
VSCP_PRIORITY_7 =  0xE0

VSCP_PRIORITY_HIGH =  0x00
VSCP_PRIORITY_LOW =   0xE0
VSCP_PRIORITY_MEDIUM = 0xC0
VSCP_PRIORITY_NORMAL = 0x60

VSCP_HEADER_PRIORITY_MASK = 0xE0

VSCP_HEADER_HARD_CODED = 0x10    # If set node nickname is hardcoded
VSCP_HEADER_NO_CRC = 0x08    # Don't calculate CRC

VSCP_NO_CRC_CALC = 0x08    # If set no CRC is calculated

VSCP_MASK_PRIORITY =  0xE0
VSCP_MASK_HARDCODED = 0x10
VSCP_MASK_NOCRCCALC = 0x08

VSCP_LEVEL1_MAXDATA = 8
VSCP_LEVEL2_MAXDATA = (512 - 25)

VSCP_CAN_ID_HARD_CODED = 0x02000000  # Hard coded bit in CAN frame id

# GUID byte positions
VSCP_GUID_MSB = 0
VSCP_GUID_LSB = 15

# VSCP Class
VSCP_CLASS1_PROTOCOL = 0
VSCP_CLASS1_ALARM           = 1
VSCP_CLASS1_SECURITY        = 2
VSCP_CLASS1_MEASUREMENT     = 10
VSCP_CLASS1_DATA            = 15
VSCP_CLASS1_INFORMATION     = 20
VSCP_CLASS1_CONTROL         = 30
VSCP_CLASS1_MULTIMEDIA      = 40
VSCP_CLASS1_AOL             = 50
VSCP_CLASS1_MEASUREMENT64   = 60
VSCP_CLASS1_MEASUREZONE     = 65
VSCP_CLASS1_MEASUREMENT32   = 70
VSCP_CLASS1_SETVALUEZONE    = 85
VSCP_CLASS1_WEATHER         = 90
VSCP_CLASS1_WEATHER_FORECAST= 95
VSCP_CLASS1_PHONE           = 100
VSCP_CLASS1_LIN             = 101
VSCP_CLASS1_DISPLAY         = 102
VSCP_CLASS1_REMOTE          = 110

# VSCP Type
VSCP_TYPE_PROTOCOL_SEGCTRL_HEARTBEAT               = 1
VSCP_TYPE_PROTOCOL_NEW_NODE_ONLINE                 = 2
VSCP_TYPE_PROTOCOL_PROBE_ACK                       = 3
VSCP_TYPE_PROTOCOL_SET_NICKNAME                    = 6
VSCP_TYPE_PROTOCOL_NICKNAME_ACCEPTED               = 7
VSCP_TYPE_PROTOCOL_DROP_NICKNAME                   = 8
VSCP_TYPE_PROTOCOL_READ_REGISTER                   = 9
VSCP_TYPE_PROTOCOL_RW_RESPONSE                     = 10
VSCP_TYPE_PROTOCOL_WRITE_REGISTER                  = 11
VSCP_TYPE_PROTOCOL_ENTER_BOOT_LOADER               = 12
VSCP_TYPE_PROTOCOL_ACK_BOOT_LOADER                 = 13
VSCP_TYPE_PROTOCOL_NACK_BOOT_LOADER                = 14
VSCP_TYPE_PROTOCOL_START_BLOCK                     = 15
VSCP_TYPE_PROTOCOL_BLOCK_DATA                      = 16
VSCP_TYPE_PROTOCOL_BLOCK_DATA_ACK                  = 17
VSCP_TYPE_PROTOCOL_BLOCK_DATA_NACK                 = 18
VSCP_TYPE_PROTOCOL_PROGRAM_BLOCK_DATA              = 19
VSCP_TYPE_PROTOCOL_PROGRAM_BLOCK_DATA_ACK          = 20
VSCP_TYPE_PROTOCOL_PROGRAM_BLOCK_DATA_NACK         = 21
VSCP_TYPE_PROTOCOL_ACTIVATE_NEW_IMAGE              = 22
VSCP_TYPE_PROTOCOL_RESET_DEVICE                    = 23
VSCP_TYPE_PROTOCOL_PAGE_READ                       = 24
VSCP_TYPE_PROTOCOL_PAGE_WRITE                      = 25
VSCP_TYPE_PROTOCOL_RW_PAGE_RESPONSE                = 26
VSCP_TYPE_PROTOCOL_HIGH_END_SERVER_PROBE           = 27
VSCP_TYPE_PROTOCOL_HIGH_END_SERVER_RESPONSE        = 28
VSCP_TYPE_PROTOCOL_INCREMENT_REGISTER              = 29
VSCP_TYPE_PROTOCOL_DECREMENT_REGISTER              = 30
VSCP_TYPE_PROTOCOL_WHO_IS_THERE                    = 31
VSCP_TYPE_PROTOCOL_WHO_IS_THERE_RESPONSE           = 32
VSCP_TYPE_PROTOCOL_GET_MATRIX_INFO                 = 33
VSCP_TYPE_PROTOCOL_GET_MATRIX_INFO_RESPONSE        = 34
VSCP_TYPE_PROTOCOL_GET_EMBEDDED_MDF                = 35
VSCP_TYPE_PROTOCOL_GET_EMBEDDED_MDF_RESPONSE       = 36
VSCP_TYPE_PROTOCOL_EXTENDED_PAGE_READ              = 37
VSCP_TYPE_PROTOCOL_EXTENDED_PAGE_WRITE             = 38
VSCP_TYPE_PROTOCOL_EXTENDED_PAGE_RESPONSE          = 39
VSCP_TYPE_PROTOCOL_GET_EVENT_INTEREST              = 40
VSCP_TYPE_PROTOCOL_GET_EVENT_INTEREST_RESPONSE     = 41
VSCP_TYPE_PROTOCOL_ACTIVATE_NEW_IMAGE_ACK          = 48
VSCP_TYPE_PROTOCOL_ACTIVATE_NEW_IMAGE_NACK         = 49
VSCP_TYPE_PROTOCOL_START_BLOCK_ACK                 = 50
VSCP_TYPE_PROTOCOL_START_BLOCK_NACK                = 51

# Class 1 (0x01) -- ALARM
VSCP_TYPE_ALARM_GENERAL                            = 0
VSCP_TYPE_ALARM_WARNING                            = 1
VSCP_TYPE_ALARM_ALARM                              = 2
VSCP_TYPE_ALARM_SOUND                              = 3
VSCP_TYPE_ALARM_LIGHT                              = 4
VSCP_TYPE_ALARM_POWER                              = 5
VSCP_TYPE_ALARM_EMERGENCY_STOP                     = 6
VSCP_TYPE_ALARM_EMERGENCY_PAUSE                    = 7
VSCP_TYPE_ALARM_EMERGENCY_RESET                    = 8
VSCP_TYPE_ALARM_EMERGENCY_RESUME                   = 9

# Class 2 (0x02) -- SECURITY
VSCP_TYPE_SECURITY_GENERAL                         = 0
VSCP_TYPE_SECURITY_MOTION                          = 1
VSCP_TYPE_SECURITY_GLASS_BREAK                     = 2
VSCP_TYPE_SECURITY_BEAM_BREAK                      = 3
VSCP_TYPE_SECURITY_SENSOR_TAMPER                   = 4
VSCP_TYPE_SECURITY_SHOCK_SENSOR                    = 5
VSCP_TYPE_SECURITY_SMOKE_SENSOR                    = 6
VSCP_TYPE_SECURITY_HEAT_SENSOR                     = 7
VSCP_TYPE_SECURITY_PANIC_SWITCH                    = 8
VSCP_TYPE_SECURITY_DOOR_OPEN                       = 9
VSCP_TYPE_SECURITY_WINDOW_OPEN                     = 10
VSCP_TYPE_SECURITY_CO_SENSOR                       = 11
VSCP_TYPE_SECURITY_FROST_DETECTED                  = 12
VSCP_TYPE_SECURITY_FLAME_DETECTED                  = 13
VSCP_TYPE_SECURITY_OXYGEN_LOW                      = 14
VSCP_TYPE_SECURITY_WEIGHT_DETECTED                 = 15
VSCP_TYPE_SECURITY_WATER_DETECTED                  = 16
VSCP_TYPE_SECURITY_CONDENSATION_DETECTED           = 17
VSCP_TYPE_SECURITY_SOUND_DETECTED                  = 18
VSCP_TYPE_SECURITY_HARMFUL_SOUND_LEVEL             = 19
VSCP_TYPE_SECURITY_TAMPER                          = 20

# Class 10 (0x0a) -- MEASUREMENT
VSCP_TYPE_MEASUREMENT_GENERAL                      = 0
VSCP_TYPE_MEASUREMENT_COUNT                        = 1
VSCP_TYPE_MEASUREMENT_LENGTH                       = 2
VSCP_TYPE_MEASUREMENT_MASS                         = 3
VSCP_TYPE_MEASUREMENT_TIME                         = 4
VSCP_TYPE_MEASUREMENT_ELECTRIC_CURRENT             = 5
VSCP_TYPE_MEASUREMENT_TEMPERATURE                  = 6
VSCP_TYPE_MEASUREMENT_AMOUNT_OF_SUBSTANCE          = 7
VSCP_TYPE_MEASUREMENT_INTENSITY_OF_LIGHT           = 8
VSCP_TYPE_MEASUREMENT_FREQUENCY                    = 9
VSCP_TYPE_MEASUREMENT_RADIOACTIVITY                = 10	# or other random event
VSCP_TYPE_MEASUREMENT_FORCE                        = 11
VSCP_TYPE_MEASUREMENT_PRESSURE                     = 12
VSCP_TYPE_MEASUREMENT_ENERGY                       = 13
VSCP_TYPE_MEASUREMENT_POWER                        = 14
VSCP_TYPE_MEASUREMENT_ELECTRICAL_CHARGE            = 15
VSCP_TYPE_MEASUREMENT_ELECTRICAL_POTENTIAL         = 16	# Voltage
VSCP_TYPE_MEASUREMENT_ELECTRICAL_CAPACITANCE       = 17
VSCP_TYPE_MEASUREMENT_ELECTRICAL_RECISTANCE        = 18
VSCP_TYPE_MEASUREMENT_ELECTRICAL_CONDUCTANCE       = 19
VSCP_TYPE_MEASUREMENT_MAGNETIC_FIELD_STRENGTH      = 20
VSCP_TYPE_MEASUREMENT_MAGNETIC_FLUX                = 21
VSCP_TYPE_MEASUREMENT_MAGNETIC_FLUX_DENSITY        = 22
VSCP_TYPE_MEASUREMENT_INDUCTANCE                   = 23
VSCP_TYPE_MEASUREMENT_FLUX_OF_LIGHT                = 24
VSCP_TYPE_MEASUREMENT_ILLUMINANCE                  = 25
VSCP_TYPE_MEASUREMENT_RADIATION_DOSE               = 26
VSCP_TYPE_MEASUREMENT_CATALYTIC_ACITIVITY          = 27
VSCP_TYPE_MEASUREMENT_VOLUME                       = 28
VSCP_TYPE_MEASUREMENT_SOUND_INTENSITY              = 29
VSCP_TYPE_MEASUREMENT_ANGLE                        = 30
VSCP_TYPE_MEASUREMENT_POSITION                     = 31
VSCP_TYPE_MEASUREMENT_SPEED                        = 32
VSCP_TYPE_MEASUREMENT_ACCELERATION                 = 33
VSCP_TYPE_MEASUREMENT_TENSION                      = 34
VSCP_TYPE_MEASUREMENT_HUMIDITY                     = 35	# Damp/moist (Hygrometer reading)
VSCP_TYPE_MEASUREMENT_FLOW                         = 36
VSCP_TYPE_MEASUREMENT_THERMAL_RESISTANCE           = 37
VSCP_TYPE_MEASUREMENT_REFRACTIVE_POWER             = 38
VSCP_TYPE_MEASUREMENT_DYNAMIC_VISCOSITY            = 39
VSCP_TYPE_MEASUREMENT_SOUND_IMPEDANCE              = 40
VSCP_TYPE_MEASUREMENT_SOUND_RESISTANCE             = 41
VSCP_TYPE_MEASUREMENT_ELECTRIC_ELASTANCE           = 42
VSCP_TYPE_MEASUREMENT_LUMINOUS_ENERGY              = 43
VSCP_TYPE_MEASUREMENT_LUMINANCE                    = 44
VSCP_TYPE_MEASUREMENT_CHEMICAL_CONCENTRATION       = 45
VSCP_TYPE_MEASUREMENT_RESERVED	                   = 46
VSCP_TYPE_MEASUREMENT_DOSE_EQVIVALENT              = 47
VSCP_TYPE_MEASUREMENT_DEWPOINT                     = 49
VSCP_TYPE_MEASUREMENT_RELATIVE_LEVEL               = 50
VSCP_TYPE_MEASUREMENT_ALTITUDE                     = 51
VSCP_TYPE_MEASUREMENT_AREA                         = 52
VSCP_TYPE_MEASUREMENT_RADIANT_INTENSITY            = 53
VSCP_TYPE_MEASUREMENT_RADIANCE                     = 54
VSCP_TYPE_MEASUREMENT_IRRADIANCE                   = 55
VSCP_TYPE_MEASUREMENT_SPECTRAL_RADIANCE            = 56
VSCP_TYPE_MEASUREMENT_SPECTRAL_IRRADIANCE          = 57


# Class 15 (0x0f) -- DATA
VSCP_TYPE_DATA_GENERAL                             = 0
VSCP_TYPE_DATA_IO                                  = 1
VSCP_TYPE_DATA_AD                                  = 2
VSCP_TYPE_DATA_DA                                  = 3
VSCP_TYPE_DATA_RELATIVE_STRENGTH                   = 4
VSCP_TYPE_DATA_SIGNAL_LEVEL                        = 5
VSCP_TYPE_DATA_SIGNAL_QUALITY                      = 6

# class 20 (0x14) -- INFORMATION
VSCP_TYPE_INFORMATION_GENERAL                      = 0
VSCP_TYPE_INFORMATION_BUTTON                       = 1
VSCP_TYPE_INFORMATION_MOUSE                        = 2
VSCP_TYPE_INFORMATION_ON                           = 3
VSCP_TYPE_INFORMATION_OFF                          = 4
VSCP_TYPE_INFORMATION_ALIVE                        = 5
VSCP_TYPE_INFORMATION_TERMINATING                  = 6
VSCP_TYPE_INFORMATION_OPENED                       = 7
VSCP_TYPE_INFORMATION_CLOSED                       = 8
VSCP_TYPE_INFORMATION_NODE_HEARTBEAT               = 9
VSCP_TYPE_INFORMATION_BELOW_LIMIT                  = 10
VSCP_TYPE_INFORMATION_ABOVE_LIMIT                  = 11
VSCP_TYPE_INFORMATION_PULSE                        = 12
VSCP_TYPE_INFORMATION_ERROR                        = 13
VSCP_TYPE_INFORMATION_RESUMED                      = 14
VSCP_TYPE_INFORMATION_PAUSED                       = 15
VSCP_TYPE_INFORMATION_SLEEP                        = 16
VSCP_TYPE_INFORMATION_GOOD_MORNING                 = 17
VSCP_TYPE_INFORMATION_GOOD_DAY                     = 18
VSCP_TYPE_INFORMATION_GOOD_AFTERNOON               = 19
VSCP_TYPE_INFORMATION_GOOD_EVENING                 = 20
VSCP_TYPE_INFORMATION_GOOD_NIGHT                   = 21
VSCP_TYPE_INFORMATION_SEE_YOU_SOON                 = 22
VSCP_TYPE_INFORMATION_GOODBYE                      = 23
VSCP_TYPE_INFORMATION_STOP                         = 24
VSCP_TYPE_INFORMATION_START                        = 25
VSCP_TYPE_INFORMATION_RESET_COMPLETED              = 26
VSCP_TYPE_INFORMATION_INTERRUPTED                  = 27
VSCP_TYPE_INFORMATION_PREPARING_TO_SLEEP           = 28
VSCP_TYPE_INFORMATION_WOKEN_UP                     = 29
VSCP_TYPE_INFORMATION_DUSK                         = 30
VSCP_TYPE_INFORMATION_DAWN                         = 31
VSCP_TYPE_INFORMATION_ACTIVE                       = 32
VSCP_TYPE_INFORMATION_INACTIVE                     = 33
VSCP_TYPE_INFORMATION_BUSY                         = 34
VSCP_TYPE_INFORMATION_IDLE                         = 35
VSCP_TYPE_INFORMATION_STREAM_DATA                  = 36
VSCP_TYPE_INFORMATION_TOKEN_ACTIVITY               = 37
VSCP_TYPE_INFORMATION_STREAM_DATA_WITH_ZONE        = 38
VSCP_TYPE_INFORMATION_CONFIRM                      = 39
VSCP_TYPE_INFORMATION_LEVEL_CHANGED                = 40
VSCP_TYPE_INFORMATION_WARNING                      = 41
VSCP_TYPE_INFORMATION_STATE                        = 42
VSCP_TYPE_INFORMATION_ACTION_TRIGGER               = 43
VSCP_TYPE_INFORMATION_SUNRISE                      = 44
VSCP_TYPE_INFORMATION_SUNSET                       = 45
VSCP_TYPE_INFORMATION_START_OF_RECORD              = 46
VSCP_TYPE_INFORMATION_END_OF_RECORD                = 47
VSCP_TYPE_INFORMATION_PRESET_ACTIVE                = 48
VSCP_TYPE_INFORMATION_DETECT                       = 49
VSCP_TYPE_INFORMATION_OVERFLOW                     = 50
VSCP_TYPE_INFORMATION_BIG_LEVEL_CHANGED            = 51
VSCP_TYPE_INFORMATION_SUNRISE_TWILIGHT_START       = 52
VSCP_TYPE_INFORMATION_SUNSET_TWILIGHT_START        = 53
VSCP_TYPE_INFORMATION_NAUTICAL_SUNRISE_TWILIGHT_START      = 54
VSCP_TYPE_INFORMATION_NAUTICAL_SUNSET_TWILIGHT_START       = 55
VSCP_TYPE_INFORMATION_ASTRONOMICAL_SUNRISE_TWILIGHT_START  = 56
VSCP_TYPE_INFORMATION_ASTRONOMICAL_SUNSET_TWILIGHT_START   = 57
VSCP_TYPE_INFORMATION_CALCULATED_NOON                      = 58
VSCP_TYPE_INFORMATION_SHUTTER_UP                   = 59
VSCP_TYPE_INFORMATION_SHUTTER_DOWN                 = 60
VSCP_TYPE_INFORMATION_SHUTTER_LEFT                 = 61
VSCP_TYPE_INFORMATION_SHUTTER_RIGHT                = 62
VSCP_TYPE_INFORMATION_SHUTTER_END_TOP              = 63
VSCP_TYPE_INFORMATION_SHUTTER_END_BOTTOM           = 64
VSCP_TYPE_INFORMATION_SHUTTER_END_MIDDLE           = 65
VSCP_TYPE_INFORMATION_SHUTTER_END_PRESET           = 66
VSCP_TYPE_INFORMATION_SHUTTER_END_LEFT             = 67
VSCP_TYPE_INFORMATION_SHUTTER_END_RIGHT            = 68

# class 30 (0x1E) -- CONTROL
VSCP_TYPE_CONTROL_GENERAL                          = 0
VSCP_TYPE_CONTROL_MUTE                             = 1
VSCP_TYPE_CONTROL_ALL_LAMPS                        = 2
VSCP_TYPE_CONTROL_OPEN                             = 3
VSCP_TYPE_CONTROL_CLOSE                            = 4
VSCP_TYPE_CONTROL_TURNON                           = 5
VSCP_TYPE_CONTROL_TURNOFF                          = 6
VSCP_TYPE_CONTROL_START                            = 7
VSCP_TYPE_CONTROL_STOP                             = 8
VSCP_TYPE_CONTROL_RESET                            = 9
VSCP_TYPE_CONTROL_INTERRUPT                        = 10
VSCP_TYPE_CONTROL_SLEEP                            = 11
VSCP_TYPE_CONTROL_WAKEUP                           = 12
VSCP_TYPE_CONTROL_RESUME                           = 13
VSCP_TYPE_CONTROL_PAUSE                            = 14
VSCP_TYPE_CONTROL_ACTIVATE                         = 15
VSCP_TYPE_CONTROL_DEACTIVATE                       = 16
VSCP_TYPE_CONTROL_DIM_LAMPS                        = 20
VSCP_TYPE_CONTROL_CHANGE_CHANNEL                   = 21
VSCP_TYPE_CONTROL_CHANGE_LEVEL                     = 22
VSCP_TYPE_CONTROL_RELATIVE_CHANGE_LEVEL            = 23
VSCP_TYPE_CONTROL_MEASUREMENT_REQUEST              = 24
VSCP_TYPE_CONTROL_STREAM_DATA                      = 25
VSCP_TYPE_CONTROL_SYNC                             = 26
VSCP_TYPE_CONTROL_ZONED_STREAM_DATA                = 27
VSCP_TYPE_CONTROL_SET_PRESET                       = 28
VSCP_TYPE_CONTROL_TOGGLE_STATE                     = 29
VSCP_TYPE_CONTROL_TIMED_PULE_ON                    = 30
VSCP_TYPE_CONTROL_TIMED_PULSE_OFF                  = 31
VSCP_TYPE_CONTROL_SET_COUNTRY_LANGUAGE	           = 32
VSCP_TYPE_CONTROL_BIG_CHANGE_LEVEL                 = 33
VSCP_TYPE_CONTROL_SHUTTER_UP                       = 34
VSCP_TYPE_CONTROL_SHUTTER_DOWN                     = 35
VSCP_TYPE_CONTROL_SHUTTER_LEFT                     = 36
VSCP_TYPE_CONTROL_SHUTTER_RIGHT                    = 37
VSCP_TYPE_CONTROL_SHUTTER_MIDDLE                   = 38
VSCP_TYPE_CONTROL_SHUTTER_PRESET                   = 39

# class 40 (0x28) -- MULTIMEDIA
VSCP_TYPE_MULTIMEDIA_GENERAL                       = 0
VSCP_TYPE_MULTIMEDIA_PLAYBACK                      = 1
VSCP_TYPE_MULTIMEDIA_NAVIGATOR_KEY_ENG             = 2
VSCP_TYPE_MULTIMEDIA_ADJUST_CONTRAST               = 3
VSCP_TYPE_MULTIMEDIA_ADJUST_FOCUS                  = 4
VSCP_TYPE_MULTIMEDIA_ADJUST_TINT                   = 5
VSCP_TYPE_MULTIMEDIA_ADJUST_COLOUR_BALANCE         = 6
VSCP_TYPE_MULTIMEDIA_ADJUST_BRIGHTNESS             = 7
VSCP_TYPE_MULTIMEDIA_ADJUST_HUE                    = 8
VSCP_TYPE_MULTIMEDIA_ADJUST_BASS                   = 9
VSCP_TYPE_MULTIMEDIA_ADJUST_TREBLE                 = 10
VSCP_TYPE_MULTIMEDIA_ADJUST_MASTER_VOLUME          = 11
VSCP_TYPE_MULTIMEDIA_ADJUST_FRONT_VOLUME           = 12
VSCP_TYPE_MULTIMEDIA_ADJUST_CENTRE_VOLUME          = 13
VSCP_TYPE_MULTIMEDIA_ADJUST_REAR_VOLUME            = 14
VSCP_TYPE_MULTIMEDIA_ADJUST_SIDE_VOLUME            = 15
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_DISK            = 20
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_TRACK           = 21
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_ALBUM           = 22
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_CHANNEL         = 23
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_PAGE            = 24
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_CHAPTER         = 25
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_SCREEN_FORMAT   = 26
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_INPUT_SOURCE    = 27
VSCP_TYPE_MULTIMEDIA_ADJUST_SELECT_OUTPUT          = 28
VSCP_TYPE_MULTIMEDIA_RECORD                        = 29
VSCP_TYPE_MULTIMEDIA_SET_RECORDING_VOLUME          = 30
VSCP_TYPE_MULTIMEDIA_TIVO_FUNCTION                 = 40
VSCP_TYPE_MULTIMEDIA_GET_CURRENT_TITLE             = 50
VSCP_TYPE_MULTIMEDIA_SET_POSITION                  = 51
VSCP_TYPE_MULTIMEDIA_GET_MEDIA_INFO                = 52
VSCP_TYPE_MULTIMEDIA_REMOVE_ITEM                   = 53
VSCP_TYPE_MULTIMEDIA_REMOVE_ALL_ITEMS              = 54
VSCP_TYPE_MULTIMEDIA_SAVE_ALBUM                    = 55
VSCP_TYPE_MULTIMEDIA_CONTROL                       = 60
VSCP_TYPE_MULTIMEDIA_CONTROL_RESPONSE              = 61

# class 50 (0x32) -- AOL
VSCP_TYPE_AOL_GENERAL                              = 0
VSCP_TYPE_AOL_UNPLUGGED_POWER                      = 1 
VSCP_TYPE_AOL_UNPLUGGED_LAN                        = 2
VSCP_TYPE_AOL_CHASSIS_INTRUSION                    = 3
VSCP_TYPE_AOL_PROCESSOR_REMOVAL                    = 4
VSCP_TYPE_AOL_ENVIRONMENT_ERROR                    = 5
VSCP_TYPE_AOL_HIGH_TEMPERATURE                     = 6
VSCP_TYPE_AOL_FAN_SPEED                            = 7
VSCP_TYPE_AOL_VOLTAGE_FLUCTUATIONS                 = 8
VSCP_TYPE_AOL_OS_ERROR                             = 9
VSCP_TYPE_AOL_POWER_ON_ERROR                       = 10
VSCP_TYPE_AOL_SYSTEM_HUNG                          = 11
VSCP_TYPE_AOL_COMPONENT_FAILURE                    = 12
VSCP_TYPE_AOL_REBOOT_UPON_FAILURE                  = 13
VSCP_TYPE_AOL_REPAIR_OPERATING_SYSTEM              = 14
VSCP_TYPE_AOL_UPDATE_BIOS_IMAGE                    = 15
VSCP_TYPE_AOL_UPDATE_DIAGNOSTIC_PROCEDURE          = 16

# class 60 (0x3C) -- CLASS1.MEASUREMENT64
# Types are the same as CLASS1.MEASUREMENT=10
VSCP_TYPE_MEASUREMENT64_GENERAL                    = 0
VSCP_TYPE_MEASUREMENT64_COUNT                      = 1
VSCP_TYPE_MEASUREMENT64_LENGTH                     = 2
VSCP_TYPE_MEASUREMENT64_MASS                       = 3
VSCP_TYPE_MEASUREMENT64_TIME                       = 4
VSCP_TYPE_MEASUREMENT64_ELECTRIC_CURRENT           = 5
VSCP_TYPE_MEASUREMENT64_TEMPERATURE                = 6
VSCP_TYPE_MEASUREMENT64_AMOUNT_OF_SUBSTANCE        = 7
VSCP_TYPE_MEASUREMENT64_INTENSITY_OF_LIGHT         = 8
VSCP_TYPE_MEASUREMENT64_FREQUENCY                  = 9
VSCP_TYPE_MEASUREMENT64_RADIOACTIVITY              = 10	# or other random event
VSCP_TYPE_MEASUREMENT64_FORCE                      = 11
VSCP_TYPE_MEASUREMENT64_PRESSURE                   = 12
VSCP_TYPE_MEASUREMENT64_ENERGY                     = 13
VSCP_TYPE_MEASUREMENT64_POWER                      = 14
VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CHARGE          = 15
VSCP_TYPE_MEASUREMENT64_ELECTRICAL_POTENTIAL       = 16	# Voltage
VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CAPACITANCE     = 17
VSCP_TYPE_MEASUREMENT64_ELECTRICAL_RECISTANCE      = 18
VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CONDUCTANCE     = 19
VSCP_TYPE_MEASUREMENT64_MAGNETIC_FIELD_STRENGTH    = 20
VSCP_TYPE_MEASUREMENT64_MAGNETIC_FLUX              = 21
VSCP_TYPE_MEASUREMENT64_MAGNETIC_FLUX_DENSITY      = 22
VSCP_TYPE_MEASUREMENT64_INDUCTANCE                 = 23
VSCP_TYPE_MEASUREMENT64_FLUX_OF_LIGHT              = 24
VSCP_TYPE_MEASUREMENT64_ILLUMINANCE                = 25
VSCP_TYPE_MEASUREMENT64_RADIATION_DOSE             = 26
VSCP_TYPE_MEASUREMENT64_CATALYTIC_ACITIVITY        = 27
VSCP_TYPE_MEASUREMENT64_VOLUME                     = 28
VSCP_TYPE_MEASUREMENT64_SOUND_INTENSITY            = 29
VSCP_TYPE_MEASUREMENT64_ANGLE                      = 30
VSCP_TYPE_MEASUREMENT64_POSITION                   = 31
VSCP_TYPE_MEASUREMENT64_SPEED                      = 32
VSCP_TYPE_MEASUREMENT64_ACCELERATION               = 33
VSCP_TYPE_MEASUREMENT64_TENSION                    = 34
VSCP_TYPE_MEASUREMENT64_HUMIDITY                   = 35	# Damp/moist (Hygrometer reading)
VSCP_TYPE_MEASUREMENT64_FLOW                       = 36
VSCP_TYPE_MEASUREMENT64_THERMAL_RESISTANCE         = 37
VSCP_TYPE_MEASUREMENT64_REFRACTIVE_POWER           = 38
VSCP_TYPE_MEASUREMENT64_DYNAMIC_VISCOSITY          = 39
VSCP_TYPE_MEASUREMENT64_SOUND_IMPEDANCE            = 40
VSCP_TYPE_MEASUREMENT64_SOUND_RESISTANCE           = 41
VSCP_TYPE_MEASUREMENT64_ELECTRIC_ELASTANCE         = 42
VSCP_TYPE_MEASUREMENT64_LUMINOUS_ENERGY            = 43
VSCP_TYPE_MEASUREMENT64_LUMINANCE                  = 44
VSCP_TYPE_MEASUREMENT64_CHEMICAL_CONCENTRATION     = 45
VSCP_TYPE_MEASUREMENT64_RESERVED	               = 46
VSCP_TYPE_MEASUREMENT64_DOSE_EQVIVALENT            = 47
VSCP_TYPE_MEASUREMENT64_DEWPOINT                   = 49
VSCP_TYPE_MEASUREMENT64_RELATIVE_LEVEL             = 50
VSCP_TYPE_MEASUREMENT64_ALTITUDE                   = 51
VSCP_TYPE_MEASUREMENT64_AREA                       = 52
VSCP_TYPE_MEASUREMENT64_RADIANT_INTENSITY          = 53
VSCP_TYPE_MEASUREMENT64_RADIANCE                   = 54
VSCP_TYPE_MEASUREMENT64_IRRADIANCE                 = 55
VSCP_TYPE_MEASUREMENT64_SPECTRAL_RADIANCE          = 56
VSCP_TYPE_MEASUREMENT64_SPECTRAL_IRRADIANCE        = 57

# class 65 (0x41) -- CLASS1.MEASUREZONE 
# Types are the same as CLASS1.MEASUREMENT=10
VSCP_TYPE_MEASUREZONE_GENERAL                     	= 0
VSCP_TYPE_MEASUREZONE_COUNT                       	= 1
VSCP_TYPE_MEASUREZONE_LENGTH                      	= 2
VSCP_TYPE_MEASUREZONE_MASS                        	= 3
VSCP_TYPE_MEASUREZONE_TIME                        	= 4
VSCP_TYPE_MEASUREZONE_ELECTRIC_CURRENT            	= 5
VSCP_TYPE_MEASUREZONE_TEMPERATURE                 	= 6
VSCP_TYPE_MEASUREZONE_AMOUNT_OF_SUBSTANCE         	= 7
VSCP_TYPE_MEASUREZONE_INTENSITY_OF_LIGHT          	= 8
VSCP_TYPE_MEASUREZONE_FREQUENCY                   	= 9
VSCP_TYPE_MEASUREZONE_RADIOACTIVITY               	= 10	# or other random event
VSCP_TYPE_MEASUREZONE_FORCE                       	= 11
VSCP_TYPE_MEASUREZONE_PRESSURE                    	= 12
VSCP_TYPE_MEASUREZONE_ENERGY                      	= 13
VSCP_TYPE_MEASUREZONE_POWER                       	= 14
VSCP_TYPE_MEASUREZONE_ELECTRICAL_CHARGE           	= 15
VSCP_TYPE_MEASUREZONE_ELECTRICAL_POTENTIAL        	= 16	# Voltage
VSCP_TYPE_MEASUREZONE_ELECTRICAL_CAPACITANCE      	= 17
VSCP_TYPE_MEASUREZONE_ELECTRICAL_RECISTANCE       	= 18
VSCP_TYPE_MEASUREZONE_ELECTRICAL_CONDUCTANCE      	= 19
VSCP_TYPE_MEASUREZONE_MAGNETIC_FIELD_STRENGTH     	= 20
VSCP_TYPE_MEASUREZONE_MAGNETIC_FLUX               	= 21
VSCP_TYPE_MEASUREZONE_MAGNETIC_FLUX_DENSITY       	= 22
VSCP_TYPE_MEASUREZONE_INDUCTANCE                  	= 23
VSCP_TYPE_MEASUREZONE_FLUX_OF_LIGHT               	= 24
VSCP_TYPE_MEASUREZONE_ILLUMINANCE                 	= 25
VSCP_TYPE_MEASUREZONE_RADIATION_DOSE              	= 26
VSCP_TYPE_MEASUREZONE_CATALYTIC_ACITIVITY         	= 27
VSCP_TYPE_MEASUREZONE_VOLUME                      	= 28
VSCP_TYPE_MEASUREZONE_SOUND_INTENSITY             	= 29
VSCP_TYPE_MEASUREZONE_ANGLE                       	= 30
VSCP_TYPE_MEASUREZONE_POSITION                    	= 31
VSCP_TYPE_MEASUREZONE_SPEED                       	= 32
VSCP_TYPE_MEASUREZONE_ACCELERATION                	= 33
VSCP_TYPE_MEASUREZONE_TENSION                     	= 34
VSCP_TYPE_MEASUREZONE_HUMIDITY                    	= 35	# Damp/moist (Hygrometer reading)
VSCP_TYPE_MEASUREZONE_FLOW                        	= 36
VSCP_TYPE_MEASUREZONE_THERMAL_RESISTANCE          	= 37
VSCP_TYPE_MEASUREZONE_REFRACTIVE_POWER            	= 38
VSCP_TYPE_MEASUREZONE_DYNAMIC_VISCOSITY           	= 39
VSCP_TYPE_MEASUREZONE_SOUND_IMPEDANCE             	= 40
VSCP_TYPE_MEASUREZONE_SOUND_RESISTANCE            	= 41
VSCP_TYPE_MEASUREZONE_ELECTRIC_ELASTANCE          	= 42
VSCP_TYPE_MEASUREZONE_LUMINOUS_ENERGY             	= 43
VSCP_TYPE_MEASUREZONE_LUMINANCE                   	= 44
VSCP_TYPE_MEASUREZONE_CHEMICAL_CONCENTRATION      	= 45
VSCP_TYPE_MEASUREZONE_RESERVED	               	  	= 46
VSCP_TYPE_MEASUREZONE_DOSE_EQVIVALENT             	= 47
VSCP_TYPE_MEASUREZONE_DEWPOINT                    	= 49
VSCP_TYPE_MEASUREZONE_RELATIVE_LEVEL              	= 50
VSCP_TYPE_MEASUREZONE_ALTITUDE                    	= 51
VSCP_TYPE_MEASUREZONE_AREA                        	= 52
VSCP_TYPE_MEASUREZONE_RADIANT_INTENSITY           	= 53
VSCP_TYPE_MEASUREZONE_RADIANCE                    	= 54
VSCP_TYPE_MEASUREZONE_IRRADIANCE                  	= 55
VSCP_TYPE_MEASUREZONE_SPECTRAL_RADIANCE           	= 56
VSCP_TYPE_MEASUREZONE_SPECTRAL_IRRADIANCE         	= 57

# class 70 (0x46) -- CLASS1.MEASUREMENT32
# Types are the same as CLASS1.MEASUREMENT=10
VSCP_TYPE_MEASUREMENT32_GENERAL                    = 0
VSCP_TYPE_MEASUREMENT32_COUNT                      = 1
VSCP_TYPE_MEASUREMENT32_LENGTH                     = 2
VSCP_TYPE_MEASUREMENT32_MASS                       = 3
VSCP_TYPE_MEASUREMENT32_TIME                       = 4
VSCP_TYPE_MEASUREMENT32_ELECTRIC_CURRENT           = 5
VSCP_TYPE_MEASUREMENT32_TEMPERATURE                = 6
VSCP_TYPE_MEASUREMENT32_AMOUNT_OF_SUBSTANCE        = 7
VSCP_TYPE_MEASUREMENT32_INTENSITY_OF_LIGHT         = 8
VSCP_TYPE_MEASUREMENT32_FREQUENCY                  = 9
VSCP_TYPE_MEASUREMENT32_RADIOACTIVITY              = 10	# or other random event
VSCP_TYPE_MEASUREMENT32_FORCE                      = 11
VSCP_TYPE_MEASUREMENT32_PRESSURE                   = 12
VSCP_TYPE_MEASUREMENT32_ENERGY                     = 13
VSCP_TYPE_MEASUREMENT32_POWER                      = 14
VSCP_TYPE_MEASUREMENT32_ELECTRICAL_CHARGE          = 15
VSCP_TYPE_MEASUREMENT32_ELECTRICAL_POTENTIAL       = 16	# Voltage
VSCP_TYPE_MEASUREMENT32_ELECTRICAL_CAPACITANCE     = 17
VSCP_TYPE_MEASUREMENT32_ELECTRICAL_RECISTANCE      = 18
VSCP_TYPE_MEASUREMENT32_ELECTRICAL_CONDUCTANCE     = 19
VSCP_TYPE_MEASUREMENT32_MAGNETIC_FIELD_STRENGTH    = 20
VSCP_TYPE_MEASUREMENT32_MAGNETIC_FLUX              = 21
VSCP_TYPE_MEASUREMENT32_MAGNETIC_FLUX_DENSITY      = 22
VSCP_TYPE_MEASUREMENT32_INDUCTANCE                 = 23
VSCP_TYPE_MEASUREMENT32_FLUX_OF_LIGHT              = 24
VSCP_TYPE_MEASUREMENT32_ILLUMINANCE                = 25
VSCP_TYPE_MEASUREMENT32_RADIATION_DOSE             = 26
VSCP_TYPE_MEASUREMENT32_CATALYTIC_ACITIVITY        = 27
VSCP_TYPE_MEASUREMENT32_VOLUME                     = 28
VSCP_TYPE_MEASUREMENT32_SOUND_INTENSITY            = 29
VSCP_TYPE_MEASUREMENT32_ANGLE                      = 30
VSCP_TYPE_MEASUREMENT32_POSITION                   = 31
VSCP_TYPE_MEASUREMENT32_SPEED                      = 32
VSCP_TYPE_MEASUREMENT32_ACCELERATION               = 33
VSCP_TYPE_MEASUREMENT32_TENSION                    = 34
VSCP_TYPE_MEASUREMENT32_HUMIDITY                   = 35	# Damp/moist (Hygrometer reading)
VSCP_TYPE_MEASUREMENT32_FLOW                       = 36
VSCP_TYPE_MEASUREMENT32_THERMAL_RESISTANCE         = 37
VSCP_TYPE_MEASUREMENT32_REFRACTIVE_POWER           = 38
VSCP_TYPE_MEASUREMENT32_DYNAMIC_VISCOSITY          = 39
VSCP_TYPE_MEASUREMENT32_SOUND_IMPEDANCE            = 40
VSCP_TYPE_MEASUREMENT32_SOUND_RESISTANCE           = 41
VSCP_TYPE_MEASUREMENT32_ELECTRIC_ELASTANCE         = 42
VSCP_TYPE_MEASUREMENT32_LUMINOUS_ENERGY            = 43
VSCP_TYPE_MEASUREMENT32_LUMINANCE                  = 44
VSCP_TYPE_MEASUREMENT32_CHEMICAL_CONCENTRATION     = 45
VSCP_TYPE_MEASUREMENT32_RESERVED	               = 46
VSCP_TYPE_MEASUREMENT32_DOSE_EQVIVALENT            = 47
VSCP_TYPE_MEASUREMENT32_DEWPOINT                   = 49
VSCP_TYPE_MEASUREMENT32_RELATIVE_LEVEL             = 50
VSCP_TYPE_MEASUREMENT32_ALTITUDE                   = 51
VSCP_TYPE_MEASUREMENT32_AREA                       = 52
VSCP_TYPE_MEASUREMENT32_RADIANT_INTENSITY          = 53
VSCP_TYPE_MEASUREMENT32_RADIANCE                   = 54
VSCP_TYPE_MEASUREMENT32_IRRADIANCE                 = 55
VSCP_TYPE_MEASUREMENT32_SPECTRAL_RADIANCE          = 56
VSCP_TYPE_MEASUREMENT32_SPECTRAL_IRRADIANCE        = 57

# class 85 (0x55) -- CLASS1.SETVALUEZONE 
# Types are the same as CLASS1.MEASUREMENT=10
VSCP_TYPE_SETVALUEZONE_GENERAL                     	= 0
VSCP_TYPE_SETVALUEZONE_COUNT                       	= 1
VSCP_TYPE_SETVALUEZONE_LENGTH                      	= 2
VSCP_TYPE_SETVALUEZONE_MASS                        	= 3
VSCP_TYPE_SETVALUEZONE_TIME                        	= 4
VSCP_TYPE_SETVALUEZONE_ELECTRIC_CURRENT            	= 5
VSCP_TYPE_SETVALUEZONE_TEMPERATURE                 	= 6
VSCP_TYPE_SETVALUEZONE_AMOUNT_OF_SUBSTANCE         	= 7
VSCP_TYPE_SETVALUEZONE_INTENSITY_OF_LIGHT          	= 8
VSCP_TYPE_SETVALUEZONE_FREQUENCY                   	= 9
VSCP_TYPE_SETVALUEZONE_RADIOACTIVITY               	= 10	# or other random event
VSCP_TYPE_SETVALUEZONE_FORCE                       	= 11
VSCP_TYPE_SETVALUEZONE_PRESSURE                    	= 12
VSCP_TYPE_SETVALUEZONE_ENERGY                      	= 13
VSCP_TYPE_SETVALUEZONE_POWER                       	= 14
VSCP_TYPE_SETVALUEZONE_ELECTRICAL_CHARGE           	= 15
VSCP_TYPE_SETVALUEZONE_ELECTRICAL_POTENTIAL        	= 16	# Voltage
VSCP_TYPE_SETVALUEZONE_ELECTRICAL_CAPACITANCE      	= 17
VSCP_TYPE_SETVALUEZONE_ELECTRICAL_RECISTANCE       	= 18
VSCP_TYPE_SETVALUEZONE_ELECTRICAL_CONDUCTANCE      	= 19
VSCP_TYPE_SETVALUEZONE_MAGNETIC_FIELD_STRENGTH     	= 20
VSCP_TYPE_SETVALUEZONE_MAGNETIC_FLUX               	= 21
VSCP_TYPE_SETVALUEZONE_MAGNETIC_FLUX_DENSITY       	= 22
VSCP_TYPE_SETVALUEZONE_INDUCTANCE                  	= 23
VSCP_TYPE_SETVALUEZONE_FLUX_OF_LIGHT               	= 24
VSCP_TYPE_SETVALUEZONE_ILLUMINANCE                 	= 25
VSCP_TYPE_SETVALUEZONE_RADIATION_DOSE              	= 26
VSCP_TYPE_SETVALUEZONE_CATALYTIC_ACITIVITY         	= 27
VSCP_TYPE_SETVALUEZONE_VOLUME                      	= 28
VSCP_TYPE_SETVALUEZONE_SOUND_INTENSITY             	= 29
VSCP_TYPE_SETVALUEZONE_ANGLE                       	= 30
VSCP_TYPE_SETVALUEZONE_POSITION                    	= 31
VSCP_TYPE_SETVALUEZONE_SPEED                       	= 32
VSCP_TYPE_SETVALUEZONE_ACCELERATION                	= 33
VSCP_TYPE_SETVALUEZONE_TENSION                     	= 34
VSCP_TYPE_SETVALUEZONE_HUMIDITY                    	= 35	# Damp/moist (Hygrometer reading)
VSCP_TYPE_SETVALUEZONE_FLOW                        	= 36
VSCP_TYPE_SETVALUEZONE_THERMAL_RESISTANCE          	= 37
VSCP_TYPE_SETVALUEZONE_REFRACTIVE_POWER            	= 38
VSCP_TYPE_SETVALUEZONE_DYNAMIC_VISCOSITY           	= 39
VSCP_TYPE_SETVALUEZONE_SOUND_IMPEDANCE             	= 40
VSCP_TYPE_SETVALUEZONE_SOUND_RESISTANCE            	= 41
VSCP_TYPE_SETVALUEZONE_ELECTRIC_ELASTANCE          	= 42
VSCP_TYPE_SETVALUEZONE_LUMINOUS_ENERGY             	= 43
VSCP_TYPE_SETVALUEZONE_LUMINANCE                   	= 44
VSCP_TYPE_SETVALUEZONE_CHEMICAL_CONCENTRATION      	= 45
VSCP_TYPE_SETVALUEZONE_RESERVED	               	  	= 46
VSCP_TYPE_SETVALUEZONE_DOSE_EQVIVALENT             	= 47
VSCP_TYPE_SETVALUEZONE_DEWPOINT                    	= 49
VSCP_TYPE_SETVALUEZONE_RELATIVE_LEVEL              	= 50
VSCP_TYPE_SETVALUEZONE_ALTITUDE                    	= 51
VSCP_TYPE_SETVALUEZONE_AREA                        	= 52
VSCP_TYPE_SETVALUEZONE_RADIANT_INTENSITY           	= 53
VSCP_TYPE_SETVALUEZONE_RADIANCE                    	= 54
VSCP_TYPE_SETVALUEZONE_IRRADIANCE                  	= 55
VSCP_TYPE_SETVALUEZONE_SPECTRAL_RADIANCE           	= 56
VSCP_TYPE_SETVALUEZONE_SPECTRAL_IRRADIANCE         	= 57


# class 90 (0x5A) -- WATHER
VSCP_TYPE_WEATHER_GENERAL                          = 0
VSCP_TYPE_WEATHER_SEASONS_WINTER                   = 1
VSCP_TYPE_WEATHER_SEASONS_SPRING                   = 2
VSCP_TYPE_WEATHER_SEASONS_SUMMER                   = 3
VSCP_TYPE_WEATHER_SEASONS_AUTUMN                   = 4
VSCP_TYPE_WEATHER_WIND_NONE                        = 5
VSCP_TYPE_WEATHER_WIND_LOW                         = 6
VSCP_TYPE_WEATHER_WIND_MEDIUM                      = 7
VSCP_TYPE_WEATHER_WIND_HIGH                        = 8
VSCP_TYPE_WEATHER_WIND_VERY_HIGH                   = 9
VSCP_TYPE_WEATHER_AIR_FOGGY                        = 10
VSCP_TYPE_WEATHER_AIR_FREEZING                     = 11
VSCP_TYPE_WEATHER_AIR_COLD                         = 12
VSCP_TYPE_WEATHER_AIR_VERY_COLD                    = 13
VSCP_TYPE_WEATHER_AIR_NORMAL                       = 14
VSCP_TYPE_WEATHER_AIR_HOT                          = 15
VSCP_TYPE_WEATHER_AIR_VERY_HOT                     = 16    
VSCP_TYPE_WEATHER_AIR_POLLUTION_LOW                = 17
VSCP_TYPE_WEATHER_AIR_POLLUTION_MEDIUM             = 18
VSCP_TYPE_WEATHER_AIR_POLLUTION_HIGH               = 19
VSCP_TYPE_WEATHER_AIR_HUMID                        = 20
VSCP_TYPE_WEATHER_AIR_DRY                          = 21
VSCP_TYPE_WEATHER_SOIL_HUMID                       = 22
VSCP_TYPE_WEATHER_SOIL_DRY                         = 23
VSCP_TYPE_WEATHER_RAIN_NONE                        = 24
VSCP_TYPE_WEATHER_RAIN_LIGHT                       = 25
VSCP_TYPE_WEATHER_RAIN_HEAVY                       = 26
VSCP_TYPE_WEATHER_RAIN_VERY_HEAVY                  = 27
VSCP_TYPE_WEATHER_SUN_NONE                         = 28
VSCP_TYPE_WEATHER_SUN_LIGHT                        = 29
VSCP_TYPE_WEATHER_SUN_HEAVY                        = 30
VSCP_TYPE_WEATHER_SNOW_NONE                        = 31
VSCP_TYPE_WEATHER_SNOW_LIGHT                       = 32
VSCP_TYPE_WEATHER_SNOW_HEAVY                       = 33
VSCP_TYPE_WEATHER_DEW_POINT                        = 34
VSCP_TYPE_WEATHER_STORM                            = 35
VSCP_TYPE_WEATHER_FLOOD                            = 36
VSCP_TYPE_WEATHER_EARTHQUAKE                       = 37
VSCP_TYPE_WEATHER_NUCLEAR_DISASTER                 = 38
VSCP_TYPE_WEATHER_FIRE                             = 39
VSCP_TYPE_WEATHER_LIGHTNING                        = 40
VSCP_TYPE_WEATHER_UV_RADIATION_LOW                 = 41
VSCP_TYPE_WEATHER_UV_RADIATION_MEDIUM              = 42
VSCP_TYPE_WEATHER_UV_RADIATION_NORMAL              = 43
VSCP_TYPE_WEATHER_UV_RADIATION_HIGH                = 44
VSCP_TYPE_WEATHER_UV_RADIATION_VERY_HIGH           = 45
VSCP_TYPE_WEATHER_WARNING_LEVEL1                   = 46
VSCP_TYPE_WEATHER_WARNING_LEVEL2                   = 47
VSCP_TYPE_WEATHER_WARNING_LEVEL3                   = 48
VSCP_TYPE_WEATHER_WARNING_LEVEL4                   = 49
VSCP_TYPE_WEATHER_WARNING_LEVEL5                   = 50
VSCP_TYPE_WEATHER_ARMAGEDON                        = 51

# class 95 (0x5F) -- WATHER FORECAST
VSCP_TYPE_WEATHER_FORECAST_GENERAL                 = 0
VSCP_TYPE_WEATHER_FORECAST_SEASONS_WINTER          = 1
VSCP_TYPE_WEATHER_FORECAST_SEASONS_SPRING          = 2
VSCP_TYPE_WEATHER_FORECAST_SEASONS_SUMMER          = 3
VSCP_TYPE_WEATHER_FORECAST_SEASONS_AUTUMN          = 4
VSCP_TYPE_WEATHER_FORECAST_WIND_NONE               = 5
VSCP_TYPE_WEATHER_FORECAST_WIND_LOW                = 6
VSCP_TYPE_WEATHER_FORECAST_WIND_MEDIUM             = 7
VSCP_TYPE_WEATHER_FORECAST_WIND_HIGH               = 8
VSCP_TYPE_WEATHER_FORECAST_WIND_VERY_HIGH          = 9
VSCP_TYPE_WEATHER_FORECAST_AIR_FOGGY               = 10
VSCP_TYPE_WEATHER_FORECAST_AIR_FREEZING            = 11
VSCP_TYPE_WEATHER_FORECAST_AIR_COLD                = 12
VSCP_TYPE_WEATHER_FORECAST_AIR_VERY_COLD           = 13
VSCP_TYPE_WEATHER_FORECAST_AIR_NORMAL              = 14
VSCP_TYPE_WEATHER_FORECAST_AIR_HOT                 = 15
VSCP_TYPE_WEATHER_FORECAST_AIR_VERY_HOT            = 16    
VSCP_TYPE_WEATHER_FORECAST_AIR_POLLUTION_LOW       = 17
VSCP_TYPE_WEATHER_FORECAST_AIR_POLLUTION_MEDIUM    = 18
VSCP_TYPE_WEATHER_FORECAST_AIR_POLLUTION_HIGH      = 19
VSCP_TYPE_WEATHER_FORECAST_AIR_HUMID               = 20
VSCP_TYPE_WEATHER_FORECAST_AIR_DRY                 = 21
VSCP_TYPE_WEATHER_FORECAST_SOIL_HUMID              = 22
VSCP_TYPE_WEATHER_FORECAST_SOIL_DRY                = 23
VSCP_TYPE_WEATHER_FORECAST_RAIN_NONE               = 24
VSCP_TYPE_WEATHER_FORECAST_RAIN_LIGHT              = 25
VSCP_TYPE_WEATHER_FORECAST_RAIN_HEAVY              = 26
VSCP_TYPE_WEATHER_FORECAST_RAIN_VERY_HEAVY         = 27
VSCP_TYPE_WEATHER_FORECAST_SUN_NONE                = 28
VSCP_TYPE_WEATHER_FORECAST_SUN_LIGHT               = 29
VSCP_TYPE_WEATHER_FORECAST_SUN_HEAVY               = 30
VSCP_TYPE_WEATHER_FORECAST_SNOW_NONE               = 31
VSCP_TYPE_WEATHER_FORECAST_SNOW_LIGHT              = 32
VSCP_TYPE_WEATHER_FORECAST_SNOW_HEAVY              = 33
VSCP_TYPE_WEATHER_FORECAST_DEW_POINT               = 34
VSCP_TYPE_WEATHER_FORECAST_STORM                   = 35
VSCP_TYPE_WEATHER_FORECAST_FLOOD                   = 36
VSCP_TYPE_WEATHER_FORECAST_EARTHQUAKE              = 37
VSCP_TYPE_WEATHER_FORECAST_NUCLEAR_DISASTER        = 38
VSCP_TYPE_WEATHER_FORECAST_FIRE                    = 39
VSCP_TYPE_WEATHER_FORECAST_LIGHTNING               = 40
VSCP_TYPE_WEATHER_FORECAST_UV_RADIATION_LOW        = 41
VSCP_TYPE_WEATHER_FORECAST_UV_RADIATION_MEDIUM     = 42
VSCP_TYPE_WEATHER_FORECAST_UV_RADIATION_NORMAL     = 43
VSCP_TYPE_WEATHER_FORECAST_UV_RADIATION_HIGH       = 44
VSCP_TYPE_WEATHER_FORECAST_UV_RADIATION_VERY_HIGH  = 45
VSCP_TYPE_WEATHER_FORECAST_WARNING_LEVEL1          = 46
VSCP_TYPE_WEATHER_FORECAST_WARNING_LEVEL2          = 47
VSCP_TYPE_WEATHER_FORECAST_WARNING_LEVEL3          = 48
VSCP_TYPE_WEATHER_FORECAST_WARNING_LEVEL4          = 49
VSCP_TYPE_WEATHER_FORECAST_WARNING_LEVEL5          = 50
VSCP_TYPE_WEATHER_FORECAST_ARMAGEDDON              = 51



# class 100 (0x64) -- PHONE
VSCP_TYPE_PHONE_GENERAL                            = 0
VSCP_TYPE_PHONE_INCOMING_CALL                      = 1
VSCP_TYPE_PHONE_OUTGOING_CALL                      = 2
VSCP_TYPE_PHONE_RING                               = 3
VSCP_TYPE_PHONE_ANSWERE                            = 4
VSCP_TYPE_PHONE_HANGUP                             = 5
VSCP_TYPE_PHONE_GIVEUP                             = 6
VSCP_TYPE_PHONE_TRANSFER                           = 7
VSCP_TYPE_PHONE_DATABASE_INFO                      = 8

# class 102 (0x66) -- DISPLAY
VSCP_TYPE_DISPLAY_GENERAL                          = 0
VSCP_TYPE_DISPLAY_CLEAR_DISPLAY                    = 1
VSCP_TYPE_DISPLAY_POSITION_CURSOR                  = 2
VSCP_TYPE_DISPLAY_WRITE_DISPLAY                    = 3
VSCP_TYPE_DISPLAY_WRITE_DISPLAY_BUFFER             = 4
VSCP_TYPE_DISPLAY_SHOW_DISPLAY_BUFFER              = 5
VSCP_TYPE_DISPLAY_SET_DISPLAY_BUFFER_PARAM         = 6
VSCP_TYPE_DISPLAY_SHOW_TEXT                        = 32
VSCP_TYPE_DISPLAY_SHOW_LED                         = 48
VSCP_TYPE_DISPLAY_SHOW_LED_COLOR                   = 49

# class 110 (0x6E) -- REMOTE
VSCP_TYPE_REMOTE_GENERAL                           = 0
VSCP_TYPE_REMOTE_RC5                               = 1
VSCP_TYPE_REMOTE_SONY12                            = 2
VSCP_TYPE_REMOTE_LIRC                              = 32
VSCP_TYPE_REMOTE_VSCP                              = 48

# class 206 (0xCE) -- GPS
VSCP_TYPE_GPS_GENERAL                              = 0
VSCP_TYPE_GPS_POSITION                             = 1
VSCP_TYPE_GPS_SATELLITES                           = 2

# class 212 (0xD4) -- WIRELESS
VSCP_TYPE_WIRELESS_GENERAL                         = 0
VSCP_TYPE_WIRELESS_GSM_CELL                        = 1

# class 506 (0x1FA) -- DIAGNOSTIC
VSCP_TYPE_DIAGNOSTIC_GENERAL                       = 0
VSCP_TYPE_DIAGNOSTIC_OVERVOLTAGE                   = 1
VSCP_TYPE_DIAGNOSTIC_UNDERVOLTAGE                  = 2
VSCP_TYPE_DIAGNOSTIC_VBUS_LOW                      = 3
VSCP_TYPE_DIAGNOSTIC_BATTERY_LOW                   = 4
VSCP_TYPE_DIAGNOSTIC_BATTERY_FULL                  = 5
VSCP_TYPE_DIAGNOSTIC_BATTERY_ERROR                 = 6
VSCP_TYPE_DIAGNOSTIC_BATTERY_OK                    = 7
VSCP_TYPE_DIAGNOSTIC_OVERCURRENT                   = 8
VSCP_TYPE_DIAGNOSTIC_CIRCUIT_ERROR                 = 9
VSCP_TYPE_DIAGNOSTIC_SHORT_CIRCUIT                 = 10
VSCP_TYPE_DIAGNOSTIC_OPEN_CIRCUIT                  = 11
VSCP_TYPE_DIAGNOSTIC_MOIST                         = 12
VSCP_TYPE_DIAGNOSTIC_WIRE_FAIL                     = 13
VSCP_TYPE_DIAGNOSTIC_WIRELESS_FAIL                 = 14
VSCP_TYPE_DIAGNOSTIC_IR_FAIL                       = 15
VSCP_TYPE_DIAGNOSTIC_1WIRE_FAIL                    = 16
VSCP_TYPE_DIAGNOSTIC_RS222_FAIL                    = 17
VSCP_TYPE_DIAGNOSTIC_RS232_FAIL                    = 18
VSCP_TYPE_DIAGNOSTIC_RS423_FAIL                    = 19
VSCP_TYPE_DIAGNOSTIC_RS485_FAIL                    = 20
VSCP_TYPE_DIAGNOSTIC_CAN_FAIL                      = 21
VSCP_TYPE_DIAGNOSTIC_LAN_FAIL                      = 22
VSCP_TYPE_DIAGNOSTIC_USB_FAIL                      = 23
VSCP_TYPE_DIAGNOSTIC_WIFI_FAIL                     = 24
VSCP_TYPE_DIAGNOSTIC_NFC_RFID_FAIL                 = 25
VSCP_TYPE_DIAGNOSTIC_LOW_SIGNAL                    = 26
VSCP_TYPE_DIAGNOSTIC_HIGH_SIGNAL                   = 27
VSCP_TYPE_DIAGNOSTIC_ADC_FAIL                      = 28
VSCP_TYPE_DIAGNOSTIC_ALU_FAIL                      = 29
VSCP_TYPE_DIAGNOSTIC_ASSERT                        = 30
VSCP_TYPE_DIAGNOSTIC_DAC_FAIL                      = 31
VSCP_TYPE_DIAGNOSTIC_DMA_FAIL                      = 32
VSCP_TYPE_DIAGNOSTIC_ETH_FAIL                      = 33
VSCP_TYPE_DIAGNOSTIC_EXCEPTION                     = 34
VSCP_TYPE_DIAGNOSTIC_FPU_FAIL                      = 35
VSCP_TYPE_DIAGNOSTIC_GPIO_FAIL                     = 36
VSCP_TYPE_DIAGNOSTIC_I2C_FAIL                      = 37
VSCP_TYPE_DIAGNOSTIC_I2S_FAIL                      = 38
VSCP_TYPE_DIAGNOSTIC_INVALID_CONFIG                = 39
VSCP_TYPE_DIAGNOSTIC_MMU_FAIL                      = 40
VSCP_TYPE_DIAGNOSTIC_NMI                           = 41
VSCP_TYPE_DIAGNOSTIC_OVERHEAT                      = 42
VSCP_TYPE_DIAGNOSTIC_PLL_FAIL                      = 43
VSCP_TYPE_DIAGNOSTIC_POR_FAIL                      = 44
VSCP_TYPE_DIAGNOSTIC_PWM_FAIL                      = 45
VSCP_TYPE_DIAGNOSTIC_RAM_FAIL                      = 46
VSCP_TYPE_DIAGNOSTIC_ROM_FAIL                      = 47
VSCP_TYPE_DIAGNOSTIC_SPI_FAIL                      = 48
VSCP_TYPE_DIAGNOSTIC_STACK_FAIL                    = 49
VSCP_TYPE_DIAGNOSTIC_LIN_FAIL                      = 50
VSCP_TYPE_DIAGNOSTIC_UART_FAIL                     = 51
VSCP_TYPE_DIAGNOSTIC_UNHANDLED_INT                 = 52
VSCP_TYPE_DIAGNOSTIC_MEMORY_FAIL                   = 53
VSCP_TYPE_DIAGNOSTIC_VARIABLE_RANGE                = 54
VSCP_TYPE_DIAGNOSTIC_WDT                           = 55
VSCP_TYPE_DIAGNOSTIC_EEPROM_FAIL                   = 56
VSCP_TYPE_DIAGNOSTIC_ENCRYPTION_FAIL               = 57
VSCP_TYPE_DIAGNOSTIC_BAD_USER_INPUT                = 58
VSCP_TYPE_DIAGNOSTIC_DECRYPTION_FAIL               = 59
VSCP_TYPE_DIAGNOSTIC_NOISE                         = 60
VSCP_TYPE_DIAGNOSTIC_BOOTLOADER_FAIL               = 61
VSCP_TYPE_DIAGNOSTIC_PROGRAMFLOW_FAIL              = 62
VSCP_TYPE_DIAGNOSTIC_RTC_FAIL                      = 63
VSCP_TYPE_DIAGNOSTIC_SYSTEM_TEST_FAIL              = 64
VSCP_TYPE_DIAGNOSTIC_SENSOR_FAIL                   = 65
VSCP_TYPE_DIAGNOSTIC_SAFESTATE                     = 66
VSCP_TYPE_DIAGNOSTIC_SIGNAL_IMPLAUSIBLE            = 67
VSCP_TYPE_DIAGNOSTIC_STORAGE_FAIL                  = 68
VSCP_TYPE_DIAGNOSTIC_SELFTEST_FAIL                 = 69
VSCP_TYPE_DIAGNOSTIC_ESD_EMC_EMI                   = 70
VSCP_TYPE_DIAGNOSTIC_TIMEOUT                       = 71
VSCP_TYPE_DIAGNOSTIC_LCD_FAIL                      = 72
VSCP_TYPE_DIAGNOSTIC_TOUCHPANEL_FAIL               = 73
VSCP_TYPE_DIAGNOSTIC_NOLOAD                        = 74
VSCP_TYPE_DIAGNOSTIC_COOLING_FAIL                  = 75
VSCP_TYPE_DIAGNOSTIC_HEATING_FAIL                  = 76
VSCP_TYPE_DIAGNOSTIC_TX_FAIL                       = 77
VSCP_TYPE_DIAGNOSTIC_RX_FAIL                       = 78
# 507 reserved for diagnostics

# class 508 (0x1FC) -- ERROR
VSCP_TYPE_ERROR_SUCCESS                            = 0
VSCP_TYPE_ERROR_ERROR                              = 1
# 2-6 reserved
VSCP_TYPE_ERROR_CHANNEL                            = 7
VSCP_TYPE_ERROR_FIFO_EMPTY                         = 8
VSCP_TYPE_ERROR_FIFO_FULL                          = 9
VSCP_TYPE_ERROR_FIFO_SIZE                          = 10
VSCP_TYPE_ERROR_FIFO_WAIT                          = 11      
VSCP_TYPE_ERROR_GENERIC                            = 12
VSCP_TYPE_ERROR_HARDWARE                           = 13
VSCP_TYPE_ERROR_INIT_FAIL                          = 14
VSCP_TYPE_ERROR_INIT_MISSING                       = 15		
VSCP_TYPE_ERROR_INIT_READY                         = 16
VSCP_TYPE_ERROR_NOT_SUPPORTED                      = 17
VSCP_TYPE_ERROR_OVERRUN                            = 18
VSCP_TYPE_ERROR_RCV_EMPTY                          = 19
VSCP_TYPE_ERROR_REGISTER                           = 20
VSCP_TYPE_ERROR_TRM_FULL                           = 21
# 22-27 reserved
VSCP_TYPE_ERROR_LIBRARY                            = 28
VSCP_TYPE_ERROR_PROCADDRESS                        = 29
VSCP_TYPE_ERROR_ONLY_ONE_INSTANCE                  = 30
VSCP_TYPE_ERROR_SUB_DRIVER                         = 31
VSCP_TYPE_ERROR_TIMEOUT                            = 32
VSCP_TYPE_ERROR_NOT_OPEN                           = 33
VSCP_TYPE_ERROR_PARAMETER                          = 34
VSCP_TYPE_ERROR_MEMORY                             = 35
VSCP_TYPE_ERROR_INTERNAL                           = 36
VSCP_TYPE_ERROR_COMMUNICATION                      = 37
VSCP_TYPE_ERROR_USER                               = 38
VSCP_TYPE_ERROR_PASSWORD                           = 39
VSCP_TYPE_ERROR_CONNECTION                         = 40   
VSCP_TYPE_ERROR_INVALID_HANDLE                     = 41
VSCP_TYPE_ERROR_OPERATION_FAILED                   = 42

# class 509 (0x1FD) -- LOG
VSCP_TYPE_LOG_GENERAL                              = 0
VSCP_TYPE_LOG_MESSAGE                              = 1
VSCP_TYPE_LOG_START                                = 2
VSCP_TYPE_LOG_STOP                                 = 3
VSCP_TYPE_LOG_LEVEL                                = 4

# class 510 (0x1FE) -- LABORATORY
VSCP_TYPE_LABORATORY_GENERAL                       = 0

# class 511 (0x1FF) -- LOCAL
VSCP_TYPE_LOCAL_GENERAL                            = 0

# Bootloaders
VSCP_BOOTLOADER_VSCP = 0x00	# VSCP boot loader algorithm
VSCP_BOOTLOADER_PIC1 = 0x01	# PIC algorithm 0
VSCP_BOOTLOADER_AVR1 = 0x10	# AVR algorithm 0
VSCP_BOOTLOADER_LPC1 = 0x20	# NXP/Philips LPC algorithm 0
VSCP_BOOTLOADER_ST =   0x30	# ST STR algorithm 0
VSCP_BOOTLOADER_NONE = 0xff

# Data format masks
VSCP_MASK_DATACODING_TYPE = 0xE0  # Bits 5,6,7
VSCP_MASK_DATACODING_UNIT = 0x18  # Bits 3,4
VSCP_MASK_DATACODING_INDEX = 0x07  # Bits 0,1,2

# Theese bits are coded in the three MSB bytes of the first data byte
# in a paket and tells the type of the data that follows.
VSCP_DATACODING_BIT = 0x00
VSCP_DATACODING_BYTE = 0x20
VSCP_DATACODING_STRING =  0x40
VSCP_DATACODING_INTEGER = 0x60
VSCP_DATACODING_NORMALIZED =   0x80
VSCP_DATACODING_SINGLE =  0xA0	# single precision float
VSCP_DATACODING_RESERVED1 = 0xC0
VSCP_DATACODING_RESERVED2 = 0xE0
# * * * Standard VSCP registers * * *

# Register defines above 0x7f
VSCP_STD_REGISTER_ALARM_STATUS =  0x80

VSCP_STD_REGISTER_MAJOR_VERSION = 0x81
VSCP_STD_REGISTER_MINOR_VERSION = 0x82
VSCP_STD_REGISTER_SUB_VERSION =   0x83

# 0x84 - 0x88
VSCP_STD_REGISTER_USER_ID =       0x84

# 0x89 - 0x8C
VSCP_STD_REGISTER_USER_MANDEV_ID =0x89

# 0x8D -0x90
VSCP_STD_REGISTER_USER_MANSUBDEV_ID = 0x8D

VSCP_STD_REGISTER_NICKNAME_ID =   0x91

VSCP_STD_REGISTER_PAGE_SELECT_MSB =    0x92
VSCP_STD_REGISTER_PAGE_SELECT_LSB =     0x93

VSCP_STD_REGISTER_FIRMWARE_MAJOR =0x94
VSCP_STD_REGISTER_FIRMWARE_MINOR =0x95
VSCP_STD_REGISTER_FIRMWARE_SUBMINOR = 0x96

VSCP_STD_REGISTER_BOOT_LOADER =   0x97
VSCP_STD_REGISTER_BUFFER_SIZE =   0x98
VSCP_STD_REGISTER_PAGES_COUNT =   0x99

# 0xd0 - 0xdf
VSCP_STD_REGISTER_GUID = 0xD0

# 0xe0 - 0xff
VSCP_STD_REGISTER_DEVICE_URL =    0xE0

# Level I Decision Matrix
VSCP_LEVEL1_DM_ROW_SIZE = 8

VSCP_LEVEL1_DM_OFFSET_OADDR =     0
VSCP_LEVEL1_DM_OFFSET_FLAGS =     1
VSCP_LEVEL1_DM_OFFSET_CLASS_MASK =2
VSCP_LEVEL1_DM_OFFSET_CLASS_FILTER =   3
VSCP_LEVEL1_DM_OFFSET_TYPE_MASK = 4
VSCP_LEVEL1_DM_OFFSET_TYPE_FILTER =   5
VSCP_LEVEL1_DM_OFFSET_ACTION =    6
VSCP_LEVEL1_DM_OFFSET_ACTION_PARAM = 7

# Bits for VSCP server 16-bit capability code
# used by CLASS1.PROTOCOL, HIGH END SERVER RESPONSE
VSCP_SERVER_CAPABILITY_TCPIP =    (1<<15)
VSCP_SERVER_CAPABILITY_UDP =      (1<<14)
VSCP_SERVER_CAPABILITY_WEB =      (1<<13)
VSCP_SERVER_CAPABILITY_WEBSOCKET =(1<<12)
VSCP_SERVER_CAPABILITY_REST =     (1<<11)
VSCP_SERVER_CAPABILITY_IP6 =      (1<<6)
VSCP_SERVER_CAPABILITY_IP4 =      (1<<5)
VSCP_SERVER_CAPABILITY_SSL =      (1<<4)
VSCP_SERVER_CAPABILITY_TWO_CONNECTIONS =  (1<<3)


# Error Codes
VSCP_ERROR_SUCCESS =          0      # All is OK
VSCP_ERROR_ERROR =           -1      # Error
VSCP_ERROR_CHANNEL  =         7      # Invalid channel
VSCP_ERROR_FIFO_EMPTY =       8      # FIFO is empty
VSCP_ERROR_FIFO_FULL =        9      # FIFO is full
VSCP_ERROR_FIFO_SIZE =       10      # FIFO size error
VSCP_ERROR_FIFO_WAIT =       11      
VSCP_ERROR_GENERIC =         12      # Generic error
VSCP_ERROR_HARDWARE =        13      # Hardware error
VSCP_ERROR_INIT_FAIL =       14      # Initialization failed
VSCP_ERROR_INIT_MISSING =    15		
VSCP_ERROR_INIT_READY =      16
VSCP_ERROR_NOT_SUPPORTED =   17      # Not supported
VSCP_ERROR_OVERRUN =         18      # Overrun
VSCP_ERROR_RCV_EMPTY =       19      # Receive buffer empty
VSCP_ERROR_REGISTER  =       20      # Register value error
VSCP_ERROR_TRM_FULL  =       21      # Transmit buffer full
VSCP_ERROR_LIBRARY  =        28      # Unable to load library
VSCP_ERROR_PROCADDRESS =     29      # Unable get library proc. address
VSCP_ERROR_ONLY_ONE_INSTANCE=30      # Only one instance allowed
VSCP_ERROR_SUB_DRIVER =      31      # Problem with sub driver call
VSCP_ERROR_TIMEOUT  =        32      # Time-out
VSCP_ERROR_NOT_OPEN  =       33      # The device is not open.
VSCP_ERROR_PARAMETER =       34      # A parameter is invalid.
VSCP_ERROR_MEMORY =          35      # Memory exhausted.
VSCP_ERROR_INTERNAL  =       36      # Some kind of internal program error
VSCP_ERROR_COMMUNICATION =   37      # Some kind of communication error
VSCP_ERROR_USER =            38      # Login error user name
VSCP_ERROR_PASSWORD  =       39      # Login error password
VSCP_ERROR_CONNECTION =      40      # Could not connect   
VSCP_ERROR_OPERATION_FAILED =42      # Operation failed for some reason

VSCP_ERROR_NOT_AUTHORIZED =  43 	 #User is not authorized
VSCP_ERROR_SYNTAX =          44		 #Invalid syntax
VSCP_ERROR_DEFINED_VAR =     45		 #Variable is already defined
VSCP_ERROR_VAR_NOT_FOUND =   46      #Variable is not found

error_description = {
    VSCP_ERROR_SUCCESS:         "All is OK",
    VSCP_ERROR_ERROR:           "Error",
    VSCP_ERROR_CHANNEL:         "Invalid channel",#not used
    VSCP_ERROR_FIFO_EMPTY:      "FIFO is empty",#not used
    VSCP_ERROR_FIFO_FULL:       "FIFO is full",#not used
    VSCP_ERROR_FIFO_SIZE:       "FIFO size error",#not used
    VSCP_ERROR_FIFO_WAIT:       "FIFO error",   #not used
    VSCP_ERROR_GENERIC:         "Generic error",#not used
    VSCP_ERROR_HARDWARE:        "Hardware error",#not used
    VSCP_ERROR_INIT_FAIL:       "Initialization failed",#not used
    VSCP_ERROR_INIT_MISSING:    "Mission initialization",#not used
    VSCP_ERROR_INIT_READY:      "Initialization is not finished",#not used
    VSCP_ERROR_NOT_SUPPORTED:   "Not supported",
    VSCP_ERROR_OVERRUN:         "Overrun",#not used
    VSCP_ERROR_RCV_EMPTY:       "Receive buffer empty",#not used
    VSCP_ERROR_REGISTER:        "Register value error",#not used
    VSCP_ERROR_TRM_FULL:        "Transmit buffer full",
    VSCP_ERROR_LIBRARY:         "Unable to load library",#not used
    VSCP_ERROR_PROCADDRESS:     "Unable get library proc. address",#not used
    VSCP_ERROR_ONLY_ONE_INSTANCE: "Only one instance allowed",#not used
    VSCP_ERROR_SUB_DRIVER:      "Problem with sub driver call",#not used
    VSCP_ERROR_TIMEOUT:         "Time-out",#not used
    VSCP_ERROR_NOT_OPEN:        "The device is not open.",#not used
    VSCP_ERROR_PARAMETER:       "A parameter is invalid.",#not used
    VSCP_ERROR_MEMORY:          "Memory exhausted.",#not used
    VSCP_ERROR_INTERNAL:        "Some kind of internal program error",#not used
    VSCP_ERROR_COMMUNICATION:   "Some kind of communication error",#not used
    VSCP_ERROR_USER:            "Login error user name",#not used
    VSCP_ERROR_PASSWORD:        "Login error password",
    VSCP_ERROR_CONNECTION:      "Could not connect   ",
    VSCP_ERROR_OPERATION_FAILED:"Operation failed for some reason",
    
    VSCP_ERROR_NOT_AUTHORIZED:  "User is not authorized",
    VSCP_ERROR_SYNTAX:          "Invalid syntax",
    VSCP_ERROR_DEFINED_VAR:     "Variable is already defined",
    VSCP_ERROR_VAR_NOT_FOUND:   "Variable is not found" 
}